import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '@/styles/Home.module.scss';
import Movie from '@/models/Movie';

const Home = ({movies}) => {
  const [id, setId] = useState(646380);

  const findMovie = async () => {
    const movie = await fetch(`/api/movies/${id}`);
    console.log(await movie.json());
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <span>Find movie with ID:</span>
        <input onChange={(e) => setId(e.target.value)} type="number" value={id} />
        <button onClick={findMovie}>Find Movie</button>

        {
          movies.map(movie => (
            <div key={movie._id}>
              <h1>{movie.title} {movie.year}</h1>
            </div>
          ))
        }

        {/* <Link href="/movie/123">
          <a>{movieValues.title} ({movieValues.year})</a>
        </Link> */}

      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const movies = await Movie.find();

  return { props: { movies: movies } }
}

export default Home;